release:
  - base-branch: 'main'
feature:
  - head-branch: ['^feat', 'feat']
fix:
  - head-branch: ['^fix', 'fix']
hotfix:
  - head-branch: ['^hotfix', 'hotfix']
refactor:
  - head-branch: ['^refactor', 'refactor']
chore:
  - head-branch: ['^chore', 'chore']
docs:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'